# Generated by Django 5.2.2 on 2025-06-06 15:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'Nom invalide')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s-]+$', 'Prénom invalide')])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('matricule', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Matricule invalide')])),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Numéro de téléphone invalide')])),
                ('carte_NIP', models.ImageField(upload_to='photos_carte_NIP/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('attestation', 'Attestation'), ('diplome', 'Diplôme')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('annee_d_obtention', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{4}$', 'Format : AAAA-AAAA')])),
                ('filiere', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{2,}$', 'Filière invalide')])),
                ('quittance', models.FileField(blank=True, null=True, upload_to='quittance/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('carte_etudiant', models.FileField(blank=True, null=True, upload_to='carte_etudiant/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('accept', models.BooleanField(default=False)),
                ('traitement', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Traitée', 'Traitée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=20)),
                ('notified', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fastretrait.etudiant')),
            ],
        ),
    ]
